### ISSUE TITLE
Unable to access 'https://github.com/input-output-hk/cardano-node.git/': Could not resolve host: github.com

### ISSUE THREAD

**Issue by ioakimov** [tdiesler/nessus-cardano#110]
### Unable to access 'https://github.com/input-output-hk/cardano-node.git/': Could not resolve host: github.com

**Code line:**
https://github.com/tdiesler/nessus-cardano/blob/d7915ee02723ed41dd08f921b99b4ee92fafa705/nix/cardano/builder-x86_64.sh#L66

**Steps to reproduce:**
1.  Change `CARDANO_VER` to `"1.33.0"` in `build-common.sh`
2.  `./build.sh "cardano-node" false`

System: _Debian 10_
Git branch: _Latest master branch of  tdiesler/nessus-cardano_ 

**Detailed logs:**
```
# Build Cardano Node for x86_64
#
# VERSION: 1.33.0-dev-amd64
# CABAL:   3.4.0.0
# GHC:     8.10.4

Checking libsodium ...
OK
Checking ghc ...
OK
Checking cabal ...
OK

Cloning into '/build/cardano-node'...
fatal: unable to access 'https://github.com/input-output-hk/cardano-node.git/': Could not resolve host: github.com
error: builder for '/nix/store/sdsb305k815f7yp59a9zvngl8vmsdmzd-cardano-1.33.0-dev.drv' failed with exit code 128;
  
error: 1 dependencies of derivation '/nix/store/wgcxbvr3493yn1k8jzqk85czcvgscndg-docker-layer-cardano-node.drv' failed to build
error: 1 dependencies of derivation '/nix/store/njsliiyv9rcyasx56m6f5z2raxxl7i57-docker-image-cardano-node.tar.gz.drv' failed to build
[ERROR] Unable to build image 'nessusio/cardano-node:1.33.0-dev-amd64'
```
![git_clone_failed](https://user-images.githubusercontent.com/16290187/149019375-413b09a4-3c70-499e-a8a2-e899235f8c96.jpg)

**Comment by ioakimov** [comment]
Indeed, problem was in my Nix configuration.
Adding `sandbox = false` to `/etc/nix/nix.conf` solve the problem.

I would like to thank you for this project.
I use it for educational purposes, to learn NIX (haven't worked with this technology before). And I must to say that it is clear that you have put a lot of effort into the project. And the solutions applicable here are quite elegant.

**Comment by tdiesler** [comment]
Thanks for flowers. The fruits of all this work manifest [here](https://astorpool.net/). 
A non-profit Cardano staking pool for the benefit of many. 

Actually, non-profit only for me. For Astor delegators its the most profitable staking pool out there (because of the extremely low cost per block of 0.4%). If you talk to your students, perhaps you like to mention that.
How to run a Cardano node on the RaspberryPi4 in a few easy steps is documented [here](https://tdiesler.gitbook.io/cardano/plain-docker/running-the-nodes)
