### ISSUE TITLE
Run node/tools images as non-root user

### ISSUE THREAD

**Issue by tdiesler** [tdiesler/nessus-cardano#33]
CrossRef: https://github.com/input-output-hk/cardano-node/issues/2584

**Comment by tdiesler** [comment]
@PyurOfHeart says on #2456 ...

> Containers are a great way to isolate workloads from each other, but a lot of those benefits are put at risk when they run as root, because being root inside the container allows one to become root on the underlying hosts. This opens up the cluster itself to vulnerabilities via malware originating from the workloads running within them.

> The best-practice way to solve this is to run containers as non-root users, and to set up pod security policies in kubernetes that prevent privileged containers from running and specifying run-as users for each pod. This way, if you happen to have a single compromised container, the blast radius is most likely limited to that container. This can have additional benefits, such as making all binaries read/execute-only for the container user so that malicious software on the host can not alter the binaries.

**Comment by tdiesler** [comment]
I looked at this and it seems to be a lot more involved than I originally thought. Here are the use cases that I want to support

1. Plain Docker with data volume
2. Pain Docker with bind mount
3. Docker Compose with managed volume
4. Kubernetes with PersistentVolumeClaim

Do we  already know how a Cardano node running as non-root can access a volume, which by default does not permit write access to non-root users?

**Comment by PyurOfHeart** [comment]
@tdiesler IIRC the default behavior differs between different cloud platforms offering managed kubernetes. I have tested the following on GCP and OCI:

* In the Pod spec, specify a GID under `securityContext.fsGroup`. This will set group ownership for all volumes mounted in the pod
* In the Pod spec, specify non-root UID and GID (respectively) under `securityContext.runAsUser` and `securityContext.runAsGroup`. Note that the run as group does not have to match the fsGroup attribute above. 

[Docs](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod)

Note that if you're trying to re-use a volume created with root permissions, it may not automatically get the correct permissions applied to it. The docs above talk about an experimental feature that defines what happens when the pod uid/gid doesn't match the volume. Might be simpler to mount the PVC to a temporary pod running with root privileges and fix up the permissions manually. (You may want to do this instead of throwing away the PV because it takes a long time and a lot of bandwidth to sync the blockchain DB)

**Comment by tdiesler** [comment]
Ok, thanks. I'll take another stab at this time permits (currently busy with plutus pioneer stuff)
You're also welcome to provide a PR of course
